services:
  pwncrates:
    build: ./pwncrates/
    environment:
      - FLASK_APP=main
    volumes:
      - ./data/pages:/pwncrates/pages:ro
      - ./data/writeups:/pwncrates/writeups
      - ./data/db:/pwncrates/db
      - ./data/challenges/:/tmp/challenges:ro
      - ./data/.git-credentials:/root/.git-credentials:ro
      - ./pwncrates/templates/:/pwncrates/templates:ro
      - ./pwncrates/static/:/pwncrates/static
      - ./data/config.toml:/pwncrates/config.toml
    profiles:
      - ''  # Default if not profile is specified.

  pwncrates-dev:
    build:
      context: ./pwncrates/
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_APP=main
    volumes:
      - ./data/pages:/pwncrates/pages:ro
      - ./data/writeups:/pwncrates/writeups
      - ./data/db:/pwncrates/db
      - ./data/challenges/:/tmp/challenges:ro
      - ./data/.git-credentials:/root/.git-credentials:ro
      - ./pwncrates/templates/:/pwncrates/templates:ro
      - ./pwncrates/static/:/pwncrates/static
      - ./data/config.toml:/pwncrates/config.toml
    profiles:
      - 'debug' # Can be specified with --profile debug
    ports:
      - "127.0.0.1:80:5000"

  pwncrates-test:
    build:
      context: ./pwncrates/
      dockerfile: Dockerfile.test
    environment:
      - FLASK_APP=main
    volumes:
      - ./data/pages:/pwncrates/pages:ro
      - ./data/writeups:/pwncrates/writeups
# We don't use an existing database for the tests
#      - ./data/db:/pwncrates/db
      - ./data/challenges/:/tmp/challenges:ro
      - ./data/.git-credentials:/root/.git-credentials:ro
      - ./pwncrates/templates/:/pwncrates/templates:ro
      - ./pwncrates/static/:/pwncrates/static
      - ./data/config.toml:/pwncrates/config.toml
      - ./tests/:/tests
    profiles:
      - 'test' # Can be specified with --profile test
    ports:
      - "127.0.0.1:80:5000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/ssl/key.pem:/root/ssl/key.pem:ro
      - ./data/ssl/cert.pem:/root/ssl/cert.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pwncrates
    profiles:
      - ''  # Default if not profile is specified.
