version: "3.2"
services:
  pwncrates:
    build: ./webapp/
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./data/pages:/webapp/pages:ro
      - ./data/writeups:/webapp/writeups
      - ./data/db:/webapp/db
      - ./data/challenges/:/tmp/challenges:ro
      - ./data/.git-credentials:/root/.git-credentials:ro
      - ./webapp/templates/:/webapp/templates:ro
      - ./webapp/static/:/webapp/static
