version: "3.2"
services:
  pwncrates:
    build: ./webapp/
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./data/pages:/webapp/pages:ro
      - ./data/writeups:/webapp/writeups:ro

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "127.0.0.1:3306:3306"