FROM python:3.11-slim-buster

RUN apt-get update && apt-get install git zip --assume-yes
RUN pip3 install pytest

RUN mkdir -p pwncrates
WORKDIR pwncrates

# Add these earlier to allow for optimizations
ADD requirements.txt .
RUN pip install -r requirements.txt

# Add the rest of the files
COPY . .

# Hack for now, put the tests outside the pwncrates folder and then import the pwncrates folder
WORKDIR /

ENTRYPOINT python -m pytest -vv tests/